In [ ]:
import numpy as np

In [ ]:
# Q.1 Convert a 1D array to a 2D array with 2 rows

a = np.array([1,3,5,4,9,8,6,7])
b = a.reshape(2,-1)

print("1D array : ")
print(a)
print("\n2D array : ")
print(b)


1D array : 
[1 3 5 4 9 8 6 7]

2D array : 
[[1 3 5 4]
 [9 8 6 7]]


In [24]:
# Q.2 Get the common items between a and b

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

c = np.intersect1d(a,b)
c

array([2, 4])

In [23]:
# Q.3 Get all items between 5 and 10 from a.

a = np.array([2, 6, 1, 9, 10, 3, 27])

b = a[(a>=5)&(a<=10)]
b

array([ 6,  9, 10])

In [27]:
# Q.4 Limit the number of items printed in python NumPy array a to a maximum of 6 elements.

a = np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])