In [ ]:
import numpy as np

In [ ]:
# transpose


In [ ]:
# reshape
a= np.array(np.random.randint(10,45,(2,4,6)))
print(a)
print(b.shape)
print(b.size)

[[[31 25 36 39 14 35]
  [30 30 35 10 16 36]
  [12 31 16 39 25 13]
  [12 21 37 37 20 11]]

 [[18 28 37 41 20 30]
  [24 20 21 24 43 26]
  [35 15 32 14 18 40]
  [22 21 29 13 12 27]]]
(4, 3, 6)
72


In [ ]:
# resize
b= np.resize(a,(4,3,6))
print(b)
print(b.shape)
print(b.size)

[[[31 29 31 16 37 43]
  [39 28 41 30 34 22]
  [41 39 21 14 27 32]]

 [[17 13 33 12 37 40]
  [18 17 32 18 26 21]
  [21 40 28 22 10 30]]

 [[29 12 13 21 28 34]
  [43 34 41 25 32 27]
  [31 29 31 16 37 43]]

 [[39 28 41 30 34 22]
  [41 39 21 14 27 32]
  [17 13 33 12 37 40]]]
(4, 3, 6)
72


In [ ]:
# flatten
b.flatten()

array([31, 29, 31, 16, 37, 43, 39, 28, 41, 30, 34, 22, 41, 39, 21, 14, 27,
       32, 17, 13, 33, 12, 37, 40, 18, 17, 32, 18, 26, 21, 21, 40, 28, 22,
       10, 30, 29, 12, 13, 21, 28, 34, 43, 34, 41, 25, 32, 27, 31, 29, 31,
       16, 37, 43, 39, 28, 41, 30, 34, 22, 41, 39, 21, 14, 27, 32, 17, 13,
       33, 12, 37, 40])

In [ ]:
# view
a=[1,2,3]
b=a
b[0]=10
print(a)
print(b)

[10, 2, 3]
[10, 2, 3]


In [ ]:
# copy
aa=[1,2,3]
bb=aa.copy()
bb[0]=10
print(aa)
print(bb)

[1, 2, 3]
[10, 2, 3]


In [ ]:
# Question 1: Given a 1D NumPy array arr_1d, extract and print the first element.

arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d[0])


1


In [ ]:
# Question 2: Given a 1D NumPy array arr_1d, extract and print the last three elements.

arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d[2:5])

[3 4 5]


In [ ]:
# Question 3: Given a 2D NumPy array arr_2d, extract and print the element at the second row and third column.

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d[1,2])


6


In [ ]:
# Question 4: Given a 2D NumPy array arr_2d, extract and print the first row.

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d[0,])


[1 2 3]


In [ ]:
# Question 5: Given a 2D NumPy array arr_2d, extract and print the last column.

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d[:,2])


[3 6 9]


In [ ]:
# Question 6: Given a 3D NumPy array arr_3d, extract and print the element at the second matrix, third row, and third column.

arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
print(arr_3d[1,2,2])

18


In [ ]:
# Question 7: Given a 3D NumPy array arr_3d, extract and print the first matrix.

arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
print(arr_3d[0,])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Question 8: Given a 3D NumPy array arr_3d, extract and print the last matrix.

arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15],[16,17,18]]])
print(arr_3d[-1,])

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [ ]:
# Question 1: Transpose Array Given a 2D NumPy array arr_2d, transpose the array and print the result.

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
a = np.transpose(arr_2d)
a

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
# Question 2: Reshape Array Given a 1D NumPy array arr_1d, reshape it into a 3x2 array and print the result.

arr_1d = np.array([1, 2, 3, 4, 5, 6])
b = np.reshape(arr_1d,(3,2))
b


array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# Question 3: Resize Array Given a 1D NumPy array arr_1d, resize it into a 3x3 array and print the result.

arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8])
c = np.resize(arr_1d,(3,3))
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 1]])

In [ ]:
# Question 4: Flatten Array Given a 2D NumPy array arr_2d, flatten it and print the result.

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
d= arr_2d.flatten()
d

array([1, 2, 3, 4, 5, 6])

In [ ]:
# Question 5: Transpose Array Given a 3D NumPy array arr_3d, transpose the array and print the result.

arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
e = np.transpose(arr_3d)
e

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [ ]:
# Question 6: Reshape Array Given a 1D NumPy array arr_1d, reshape it into a 4x3 array and print the result.

arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

f = np.reshape(arr_1d,(4,3))
f

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
# Question 7: Resize Array Given a 2D NumPy array arr_2d, resize it into a 4x4 array and print the result.

arr_2d = np.array([[1, 2], [3, 4]])
g = np.resize(arr_2d,(4,4))
g

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [ ]:
# Question 8: Flatten Array Given a 3D NumPy array arr_3d, flatten it and print the result.

arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
h = arr_3d.flatten()
h

array([1, 2, 3, 4, 5, 6, 7, 8])